Locales['de'] = {
  -- Cloackroom
  ['cloakroom'] = 'Garderobe',
  ['citizen_wear'] = 'Zivilkleidung',
  ['police_wear'] = 'Arbeitskleidung',
  ['gilet_wear'] = 'Warnweste',
  ['bullet_wear'] = 'schusssichere Weste',
  ['no_outfit'] = 'Es gibt keine Arbeitskleidung die dir passt!!',
  ['open_cloackroom'] = 'Drücke ~INPUT_CONTEXT~ um dich umzuziehen',
  -- Armory
  ['remove_object'] = 'Nimm Objekt',
  ['deposit_object'] = 'Lagere Objekt ein',
  ['get_weapon'] = 'Waffen holen',
  ['put_weapon'] = 'Waffen bringen',
  ['buy_weapons'] = 'Waffen kaufen',
  ['armory'] = 'Waffenkammer',
  ['open_armory'] = 'Drücke ~INPUT_CONTEXT~ um die Waffenkammer zu öffnen',
  ['armory_owned'] = 'im Besitz',
  ['armory_free'] = 'frei',
  ['armory_item'] = '$%s',
  ['armory_weapontitle'] = 'Waffenschrank - Kaufe Waffe',
  ['armory_componenttitle'] = 'Waffenschrank - Waffenaufsätze',
  ['armory_bought'] = 'Du hast ein ~y~%s~s~ for ~g~$%s~s~ gekauft',
  ['armory_money'] = 'Du kannst dir die Waffe nicht leisten!',
  ['armory_hascomponent'] = 'Du hast diesen Aufsatz ausgerüstet!',
  ['get_weapon_menu'] = 'Waffenschrank - Waffe zurücknehmen',
  ['put_weapon_menu'] = 'Waffenschrank - Waffe lagern',
  -- Vehicles
  ['vehicle_menu'] = 'Fahrzeuge',
  ['vehicle_blocked'] = 'Alle verfügbaren Spawnpunkte sind blockiert!',
  ['garage_prompt'] = 'Drücke ~INPUT_CONTEXT~ um auf ~y~Fahrzeuginteraktionen~s~ zuzugreifen',
  ['garage_title'] = 'Fahrzeuginteraktionen',
  ['garage_stored'] = 'gelagert',   
  ['garage_notstored'] = 'nicht in der Garage',
  ['garage_storing'] = 'Wir versuchen das Fahrzeug zu lagern, sorge dafür, dass sich keine Spieler in der Umgebung befinden!',
  ['garage_has_stored'] = 'Das Fahrzeug befindet sich in der Garage',
  ['garage_has_notstored'] = 'In der Nähe wurden keine Fahrzeuge gefunden, die du besitzt!',
  ['garage_notavailable'] = 'Dein Fahrzeug befindet sich nicht in der Garage.',
  ['garage_blocked'] = 'Es gibt keine verfügbaren Spawnpunkte!',
  ['garage_empty'] = 'Es befinden sich keine Fahrzeuge in deiner Garage',
  ['garage_released'] = 'Dein Fahrzeug wurde aus der Garage geparkt.',
  ['garage_store_nearby'] = 'Kein Fahrzeug in der Nähe.',
  ['garage_storeditem'] = 'Öffne Garage',
  ['garage_storeitem'] = 'Lagere Fahrzeug in der Garage',
  ['garage_buyitem'] = 'Fahrzeughändler',
  ['garage_notauthorized'] = 'Du bist nicht autorisiert diese Art von Fahrzeugen zu kaufen.',
  ['helicopter_prompt'] = 'Drücke ~INPUT_CONTEXT~ um auf ~y~Helikopterinteraktionen~s~. zuzugreifen',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'Fahrzeughändler',
  ['vehicleshop_confirm'] = 'Möchtest du dieses Fahrzeug kaufen?',
  ['vehicleshop_bought'] = 'Du hast ~y~%s~s~ für ~r~$%s~s~ gekauft',
  ['vehicleshop_money'] = 'Du kannst dir das Fahrzeug nicht leisten',
  ['vehicleshop_awaiting_model'] = 'Das Fahrzeug ist gerade am ~g~Runterladen & Laden~s~ Warte bitte.',
  ['confirm_no'] = 'Nein',
  ['confirm_yes'] = 'Ja', 
  -- Service
  ['service_max'] = 'Du kannst dem Dienst nich beitreten, maximale Polizisten im Dienst: %s/%s',
  ['service_not'] = 'Du bist ~r~NICHT~w~ im Dienst.',
  ['service_anonunce'] = 'Dienstinformationen',
  ['service_in'] = 'Du bist ~g~JETZT~w~ im Dienst',
  ['service_in_announce'] = 'Dein Boss hat den Dienst ~g~BETRETEN~w~!',
  ['service_out'] = 'Du hast den Dienst ~r~VERLASSEN~w~.',
  ['service_out_announce'] = 'Dein Boss hat den Dienst ~r~VERLASSEN~w~.',
  -- Action Menu
  ['citizen_interaction'] = 'Zivilistenaktionen',
  ['vehicle_interaction'] = 'Fahrzeuginteraktionen',
  ['object_spawner'] = 'Objekt-Spawner',

  ['id_card'] = 'ID Karte',
  ['search'] = 'Suche',
  ['handcuff'] = 'Festnehmen / Freilassen',
  ['drag'] = 'Führen',
  ['put_in_vehicle'] = 'In Fahrzeug setzen',
  ['out_the_vehicle'] = 'aus dem Fahrzeug rausnehmen',
  ['fine'] = 'Strafe',
  ['unpaid_bills'] = 'Verwalte unbezahlte Rechnungen',
  ['license_check'] = 'Verwalte Lizenzen',
  ['license_revoke'] = 'Lizenz entziehen',
  ['license_revoked'] = 'Deine ~b~%s~s~ wurde ~y~entzogen~s~!',
  ['licence_you_revoked'] = 'Du hast eine ~b~%s~s~ entzogen, die ~y~%s~s~ gehörte.',
  ['no_players_nearby'] = 'keine Spieler in der Nähe',
  ['being_searched'] = 'Du wirst von der ~b~Polizei~s~ ~y~untersucht~s~ ',
  -- Vehicle interaction
  ['vehicle_info'] = 'Fahrzeuginformationen',
  ['pick_lock'] = 'Fahrzeug öffnen',
  ['vehicle_unlocked'] = 'Fahrzeug ~g~offen~s~',
  ['no_vehicles_nearby'] = 'Keine Fahrzeuge in der Nähe',
  ['impound'] = 'Beschlagnahme Fahrzeug',
  ['impound_prompt'] = 'Drücke ~INPUT_CONTEXT~ um die ~y~Beschlagnahmung~s~ zu widerrufen.',
  ['impound_canceled'] = 'Du hast die Beschlagnahmung abgebrochen',
  ['impound_canceled_moved'] = 'Die Beschlangnahmung wurde abgebrochen, weil das Fahrzeug bewegt wurde. ',
  ['impound_successful'] = 'Du hast das Fahrzeug beschlagnahmt',
  ['search_database'] = 'Fahrzeuginformationen',
  ['search_database_title'] = 'Fahrzeuginformationen - Suche mit Kennzeichen',
  ['search_database_error_invalid'] = 'Das ist ~r~kein~s~ a ~y~gültiges~s~ Kennzeichen',
  -- Traffic interaction
  ['traffic_interaction'] = 'Straßeninteraktionen',
  ['cone'] = 'Hütchen',
  ['barrier'] = 'Barriere',
  ['spikestrips'] = 'Nagelband',
  ['box'] = 'Box',
  ['cash'] = 'Box mit Geld',
  -- ID Card Menu
  ['name'] = 'Name: %s',
  ['job'] = 'Beruf: %s',
  ['sex'] = 'Geschlecht: %s',
  ['dob'] = 'Geburtsdatum: %s',
  ['height'] = 'Größe: %s',
  ['bac'] = 'Promille: %s',
  ['unknown'] = 'unbekannt',
  ['male'] = 'männlich',
  ['female'] = 'weiblich',
  -- Body Search Menu
  ['guns_label'] = '--- Waffen ---',
  ['inventory_label'] = '--- Inventar ---',
  ['license_label'] = ' --- Lizenzen ---',
  ['confiscate'] = 'konfeszieren %s',
  ['confiscate_weapon'] = 'Konfesziere %s mit %s Schuss',
  ['confiscate_inv'] = 'Konfesziere %sx %s',
  ['confiscate_dirty'] = 'Schwarzgeld konfesziert: <span style="color:red;">$%s</span>',
  ['you_confiscated'] = 'Du hast ~y~%sx~s~ ~b~%s~s~ von ~b~%s~s~ konfesziert',
  ['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ wurde von ~y~%s~s~ konfesziert',
  ['you_confiscated_account'] = 'Du hast ~g~$%s~s~ (%s) von ~b~%s~s~ konfesziert',
  ['got_confiscated_account'] = '~g~$%s~s~ (%s) wurde von ~y~%s~s~ konfesziert',
  ['you_confiscated_weapon'] = 'Du hast ~b~%s~s~ von ~b~%s~s~ mit ~o~%s~s~ Schuss konfesziert',
  ['got_confiscated_weapon'] = 'Deine ~b~%s~s~ mit ~o~%s~s~ Schuss wurde von ~y~%s~s~ konfesziert',
  ['traffic_offense'] = 'Verkehrsverstoß',
  ['minor_offense'] = 'geringer Verstoß',
  ['average_offense'] = 'normaler Verstoß',
  ['major_offense'] = 'hohes Verstoß',
  ['fine_total'] = 'Strafe: %s',
  -- Vehicle Info Menu
  ['plate'] = 'Kennzeichen: %s',
  ['owner_unknown'] = 'Besitzer: unbekannt',
  ['owner'] = 'Besitzer: %s',
  -- Boss Menu
  ['open_bossmenu'] = 'Drücke ~INPUT_CONTEXT~ um das Menü zu öffnen',
  ['quantity_invalid'] = 'ungültige Menge',
  ['have_withdrawn'] = 'Du hast ~y~%sx~s~ ~b~%s~s~ genommen',
  ['have_deposited'] = 'Du hast ~y~%sx~s~ ~b~%s~s~ abgegeben',
  ['quantity'] = 'Menge',
  ['inventory'] = 'Inventar',
  ['police_stock'] = 'Polizeilager',
  -- Misc
  ['remove_prop'] = 'Drücke ~INPUT_CONTEXT~ um das Objekt zu entfernen',
  ['map_blip'] = 'Polizeistation',
  ['unrestrained_timer'] = 'Du fühlst, dass deine Handschellen sich langsam lösen und verschwinden.',
  -- Notifications
  ['alert_police'] = 'Polizei alarmieren',
  ['phone_police'] = 'Polizei',
}
